local config = require("nvim-header-formatter.config")

describe("config.merge", function()
  it("returns defaults when opts is nil", function()
    local m = config.merge(nil)
    assert.are.same(config.defaults.keymap_prefix, m.keymap_prefix)
    assert.are.same(config.defaults.levels, m.levels)
    assert.are.same(config.defaults.ft, m.ft)
  end)

  it("overrides keymap_prefix only", function()
    local m = config.merge({ keymap_prefix = "<leader>x" })
    assert.are.same("<leader>x", m.keymap_prefix)
    assert.are.same(config.defaults.levels, m.levels)
    assert.are.same(config.defaults.ft, m.ft)
  end)

  it("overrides levels only", function()
    local m = config.merge({ levels = { 2 } })
    assert.are.same(config.defaults.keymap_prefix, m.keymap_prefix)
    assert.are.same({ 2 }, m.levels)
    assert.are.same(config.defaults.ft, m.ft)
  end)

  it("overrides ft only", function()
    local m = config.merge({ ft = { "markdown", "markdown.mdx" } })
    assert.are.same(config.defaults.keymap_prefix, m.keymap_prefix)
    assert.are.same(config.defaults.levels, m.levels)
    assert.are.same({ "markdown", "markdown.mdx" }, m.ft)
  end)
end)